const EthernetSwitchProducts = [
    {Model: "CWGE10FX2TX8MS", Hardened: "No", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CWGE10FX2TX8MSPOE", Hardened: "No", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CWGE26FX2TX24MS", Hardened: "No", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "24x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CWGE26FX2TX24MSPOE", Hardened: "No", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "24x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CWGE26FX2TX24MSPOE+", Hardened: "No", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "24x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CWGE28MS", Hardened: "No", Managed: "Yes", Fiber_Ports: "24x GE", Copper_Ports: "4x GE", Combo_Ports: "4x GE", PoE: "No"},
    {Model: "CNXE2GE2TX8MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "2x 10G", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE2FE4SMS", Hardened: "Yes", Managed: "No", Fiber_Ports: "2x GE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE2FE4SMSPOE", Hardened: "Yes", Managed: "No", Fiber_Ports: "2x GE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE2FE4SMSPOEHO", Hardened: "Yes", Managed: "No", Fiber_Ports: "2x GE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "60W"},
    {Model: "CNGE2FE8MSPOE+", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "8x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE3FE7MS3", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "7x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE3FE8MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE3FE8MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE3FE8MSPOE/24", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE3FE8MSPOEHO", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x FE", Combo_Ports: "0", PoE: "60W"},
    {Model: "CNGE4US", Hardened: "Yes", Managed: "No", Fiber_Ports: "4x GE", Copper_Ports: "0", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE4TX4US/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "4x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE4+2SMS/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "2x GE", Copper_Ports: "4x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE4+2SMSPOE/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "2x GE", Copper_Ports: "4x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE4+2SMSPOEHO/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "2x GE", Copper_Ports: "4x GE", Combo_Ports: "0", PoE: "60W"},
    {Model: "CNGE5MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "0", Copper_Ports: "3x GE", Combo_Ports: "2x GE", PoE: "No"},
    {Model: "CNGE6FX2TX4POE", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x GE", Copper_Ports: "4x GE", Combo_Ports: "1x GE", PoE: "30W"},
    {Model: "CNGE6FX2TX4MSP", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "4x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE8US", Hardened: "Yes", Managed: "No", Fiber_Ports: "8x GE", Copper_Ports: "0", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE8MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "0", Copper_Ports: "4x GE", Combo_Ports: "4x GE", PoE: "No"},
    {Model: "CNGE8FX4TX4MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "4x GE", Copper_Ports: "4x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE11FX3TX8MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE11FX3TX8MSP/24", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE11FX3TX8MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE11FX3TX8MSPOE/24", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE11FX3TX8MSPOEHO", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "3x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "60W"},
    {Model: "CNGE20MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "12x GE", Copper_Ports: "8x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE20FX4TX16MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "4x GE", Copper_Ports: "16x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE20FX4TX16MSP", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "4x GE", Copper_Ports: "16x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE24MS2", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "8x GE", Copper_Ports: "0", Combo_Ports: "16x GE", PoE: "No"},
    {Model: "CNGE24FX12TX12MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "12x GE", Copper_Ports: "12x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE24FX12TX12MS/12", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "12x GE", Copper_Ports: "12x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNGE24FX12TX12MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "12x GE", Copper_Ports: "12x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE24FX12TX12MSPOE/48", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "12x GE", Copper_Ports: "12x GE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNGE26FX2TX24MSP", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "2x GE", Copper_Ports: "22x GE", Combo_Ports: "2x GE", PoE: "30W"},
    {Model: "CNGE28FX4TX24MS2", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "4x GE", Copper_Ports: "24x GE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4SMS", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4SMSPOE", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNFE4FX4US", Hardened: "Yes", Managed: "No", Fiber_Ports: "4x FE", Copper_Ports: "0", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4FX2TX2US", Hardened: "Yes", Managed: "No", Fiber_Ports: "2x FE", Copper_Ports: "2x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4+1SMSM2", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4+1SMSM2POE", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNFE4+1SMSM2/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4+1SMSM2POE/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNFE4+1SMSS2", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4+1SMSS2POE", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNFE4+1SMSS2/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE4+1SMSS2POE/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "1x FE", Copper_Ports: "4x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CNFE5SMS", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "5x FE", Combo_Ports: "0", PoE: "No"},
    {Model: "CNFE5SMSPOE", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "5x FE", Combo_Ports: "0", PoE: "30W"},
    {Model: "CWX28F4T24MPB", Hardened: "No", Managed: "Yes", Fiber_Ports: "4x 10G", Copper_Ports: "24x GE", Combo_Ports: "0", PoE: "90W"},
    {Model: "CWX52F4T48MP", Hardened: "No", Managed: "Yes", Fiber_Ports: "4x 10G", Copper_Ports: "48x GE", Combo_Ports: "0", PoE: "90W"},
  ];

  export default EthernetSwitchProducts;