const EthernetSwitchProducts = [
    {Model: "CWGE10FX2TX8MS", Hardened: "No", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "100-240 VAC"},
    {Model: "CWGE10FX2TX8MSPOE", Hardened: "No", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "100-240 VAC"},
    {Model: "CWGE26FX2TX24MS", Hardened: "No", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(24) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "100-240 VAC"},
    {Model: "CWGE26FX2TX24MSPOE (OBSOLETE)", Hardened: "No", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(24) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "100-240 VAC"},
    {Model: "CWGE26FX2TX24MSPOE+ (OBSOLETE)", Hardened: "No", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(24) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "100-240 VAC"},
    {Model: "CWGE28MS", Hardened: "No", Managed: "Yes", Fiber_Ports: "(24) GE", Copper_Ports: "(4) GE", Combo_Ports: "(4) GE", PoE: "No", Operating_Voltage: "100-240 VAC"},
    {Model: "CNXE2GE2TX8MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(2) 10G", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "50-57 VDC"},
    {Model: "CNGE2FE4SMS", Hardened: "Yes", Managed: "No", Fiber_Ports: "(2) GE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12-24 VDC"},
    {Model: "CNGE2FE4SMSPOE", Hardened: "Yes", Managed: "No", Fiber_Ports: "(2) GE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE2FE4SMSPOEHO", Hardened: "Yes", Managed: "No", Fiber_Ports: "(2) GE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "60W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE2FE8MSPOE+", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(8) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE3FE7MS3", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(7) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12-48 VDC"},
    {Model: "CNGE3FE8MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12-57 VDC"},
    {Model: "CNGE3FE8MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE3FE8MSPOE/24", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "24 VDC"},
    {Model: "CNGE3FE8MSPOEHO", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) FE", Combo_Ports: "0", PoE: "60W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE4US", Hardened: "Yes", Managed: "No", Fiber_Ports: "(4) GE", Copper_Ports: "0", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNGE4TX4US/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "(4) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-36 VDC"},
    {Model: "CNGE4+2SMS/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "(2) GE", Copper_Ports: "(4) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-36 VDC"},
    {Model: "CNGE4+2SMSPOE/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "(2) GE", Copper_Ports: "(4) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-56 VDC"},
    {Model: "CNGE4+2SMSPOEHO/M", Hardened: "Yes", Managed: "No", Fiber_Ports: "(2) GE", Copper_Ports: "(4) GE", Combo_Ports: "0", PoE: "60W", Operating_Voltage: "48-56 VDC"},
    {Model: "CNGE5MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "0", Copper_Ports: "(3) GE", Combo_Ports: "(2) GE", PoE: "No", Operating_Voltage: "12-48 VDC"},
    {Model: "CNGE6FX2TX4POE", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) GE", Copper_Ports: "(4) GE", Combo_Ports: "(1) GE", PoE: "30W", Operating_Voltage: "48-56 VDC"},
    {Model: "CNGE6FX2TX4MSP", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(4) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE8US", Hardened: "Yes", Managed: "No", Fiber_Ports: "(8) GE", Copper_Ports: "0", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNGE8MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "0", Copper_Ports: "(4) GE", Combo_Ports: "(4) GE", PoE: "No", Operating_Voltage: "12-48 VDC"},
    {Model: "CNGE8FX4TX4MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(4) GE", Copper_Ports: "(4) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12-48 VDC / 24 VAC"},
    {Model: "CNGE11FX3TX8MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12-57 VDC"},
    {Model: "CNGE11FX3TX8MSP/24", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "24 VDC"},
    {Model: "CNGE11FX3TX8MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE11FX3TX8MSPOE/24", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "24 VDC"},
    {Model: "CNGE11FX3TX8MSPOEHO", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(3) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "60W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE20MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(12) GE", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12-48 VDC"},
    {Model: "CNGE20FX4TX16MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(4) GE", Copper_Ports: "(16) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12-48 VDC"},
    {Model: "CNGE20FX4TX16MSP", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(4) GE", Copper_Ports: "(16) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE24MS2", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(8) GE", Copper_Ports: "0", Combo_Ports: "(16) GE", PoE: "No", Operating_Voltage: "100-240 VAC / 36-72 VDC"},
    {Model: "CNGE24FX12TX12MS", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(12) GE", Copper_Ports: "(12) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "100-240 VAC"},
    {Model: "CNGE24FX12TX12MS/12", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(12) GE", Copper_Ports: "(12) GE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "12 VDC"},
    {Model: "CNGE24FX12TX12MSPOE", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(12) GE", Copper_Ports: "(12) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "100-240 VAC / 48-57 VDC"},
    {Model: "CNGE24FX12TX12MSPOE/48", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(12) GE", Copper_Ports: "(12) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48-57 VDC"},
    {Model: "CNGE26FX2TX24MSPOE1", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(22) GE", Combo_Ports: "(2) GE", PoE: "30W", Operating_Voltage: "100-240 VAC"},
    {Model: "CNFE4SMS", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE4SMSPOE", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48 VDC"},
    {Model: "CNFE4FX4US", Hardened: "Yes", Managed: "No", Fiber_Ports: "(4) FE", Copper_Ports: "0", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE4FX2TX2US", Hardened: "Yes", Managed: "No", Fiber_Ports: "(2) FE", Copper_Ports: "(2) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE4+1SMSM2", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE4+1SMSM2POE", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48 VDC"},
    {Model: "CNFE4+1SMSM2/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE4+1SMSM2POE/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48 VDC"},
    {Model: "CNFE4+1SMSS2", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE4+1SMSS2POE", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48 VDC"},
    {Model: "CNFE4+1SMSS2/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE4+1SMSS2POE/SC", Hardened: "Yes", Managed: "No", Fiber_Ports: "(1) FE", Copper_Ports: "(4) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48 VDC"},
    {Model: "CNFE5SMS", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "(5) FE", Combo_Ports: "0", PoE: "No", Operating_Voltage: "9-24 VDC"},
    {Model: "CNFE5SMSPOE", Hardened: "Yes", Managed: "No", Fiber_Ports: "0", Copper_Ports: "(5) FE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "48 VDC"},
    {Model: "CWG26F4T22M", Hardened: "No", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(22) GE", Combo_Ports: "(2) GE", PoE: "No", Operating_Voltage: "100-240 VAC"},
    {Model: "CWG26F4T22MP", Hardened: "No", Managed: "Yes", Fiber_Ports: "(2) GE", Copper_Ports: "(22) GE", Combo_Ports: "(2) GE", PoE: "30W", Operating_Voltage: "100-240 VAC"},
    {Model: "CWX28F4T24MPB", Hardened: "No", Managed: "Yes", Fiber_Ports: "(4) 10G", Copper_Ports: "(24) GE", Combo_Ports: "0", PoE: "90W", Operating_Voltage: "100-240 VAC"},
    {Model: "CWX52F4T48MP", Hardened: "No", Managed: "Yes", Fiber_Ports: "(4) 10G", Copper_Ports: "(48) GE", Combo_Ports: "0", PoE: "30W", Operating_Voltage: "100-240 VAC"},
    {Model: "CNGE10FX2TX8MSBT", Hardened: "Yes", Managed: "Yes", Fiber_Ports: "(2) 2.5G", Copper_Ports: "(8) GE", Combo_Ports: "0", PoE: "90W", Operating_Voltage: "52-57 VDC"},
  ];

  export default EthernetSwitchProducts;