const SFPProducts = [
    { Model: "SFP-1", dataRate: "GE", txMedium: "Copper", fibers: "N/A", optics: "RJ-45", pathLength: "100 m", Tx: "N/A", Rx: "N/A" },
    { Model: "SFP-10A", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "20 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-10B", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "20 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-10G-BX10-D", dataRate: "10G", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "10 km", Tx: "1330", Rx: "1270" },
    { Model: "SFP-10G-BX10-U", dataRate: "10G", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "10 km", Tx: "1270", Rx: "1330" },
    { Model: "SFP-10G-BX40-D", dataRate: "10G", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "40 km", Tx: "1330", Rx: "1270" },
    { Model: "SFP-10G-BX40-U", dataRate: "10G", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "40 km", Tx: "1270", Rx: "1330" },
    { Model: "SFP-10G-ER", dataRate: "10G", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "40 km", Tx: "1550", Rx: "1550" },
    { Model: "SFP-10G-LR", dataRate: "10G", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "10 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-10G-SR", dataRate: "10G", txMedium: "Multimode", fibers: "2 strands", optics: "LC", pathLength: "26/300 m", Tx: "850", Rx: "850" },
    { Model: "SFP-10G-ZR", dataRate: "10G", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "80 km", Tx: "1550", Rx: "1550" },
    { Model: "SFP-12A", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "20 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-12B", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "20 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-14A", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "20 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-14B", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "20 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-16", dataRate: "GE", txMedium: "Multimode", fibers: "2 strands", optics: "LC", pathLength: "275/550 m", Tx: "850", Rx: "850" },
    { Model: "SFP-18A", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "60 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-18B", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "60 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-1A", dataRate: "FE", txMedium: "Copper", fibers: "N/A", optics: "RJ-45", pathLength: "100 m", Tx: "N/A", Rx: "N/A" },
    { Model: "SFP-2", dataRate: "FE", txMedium: "Multimode", fibers: "2 strands", optics: "LC", pathLength: "2 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-20A", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "60 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-20B", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "60 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-22A", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "60 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-22B", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "60 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-24A", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "60 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-24B", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "60 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-26A", dataRate: "FE", txMedium: "Multimode", fibers: "1 strand", optics: "SC", pathLength: "2 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-26B", dataRate: "FE", txMedium: "Multimode", fibers: "1 strand", optics: "SC", pathLength: "2 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-3", dataRate: "FE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "20 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-36A", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "20 km", Tx: "1310", Rx: "1550" },
    { Model: "SFP-36B", dataRate: "FE", txMedium: "Singlemode", fibers: "1 strand", optics: "SC", pathLength: "20 km", Tx: "1550", Rx: "1310" },
    { Model: "SFP-4", dataRate: "FE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "40 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-46", dataRate: "GE", txMedium: "Multimode", fibers: "2 strands", optics: "LC", pathLength: "2 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-48A", dataRate: "GE", txMedium: "Multimode", fibers: "1 strand", optics: "LC", pathLength: "275/550 m", Tx: "1310", Rx: "1550" },
    { Model: "SFP-48B", dataRate: "GE", txMedium: "Multimode", fibers: "1 strand", optics: "LC", pathLength: "275/550 m", Tx: "1550", Rx: "1310" },
    { Model: "SFP-5", dataRate: "FE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "80 km", Tx: "1550", Rx: "1550" },
    { Model: "SFP-6", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "15 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-7", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "40 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-8", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "70 km", Tx: "1550", Rx: "1550" },
    { Model: "SFP-9", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "120 km", Tx: "1550", Rx: "1550" },
    { Model: "SFP-BX-D", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "10 km", Tx: "1490", Rx: "1310" },
    { Model: "SFP-BX-U", dataRate: "GE", txMedium: "Singlemode", fibers: "1 strand", optics: "LC", pathLength: "10 km", Tx: "1310", Rx: "1490" },
    { Model: "SFP-EX", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "40 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-LH", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "20 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-LX", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "10 km", Tx: "1310", Rx: "1310" },
    { Model: "SFP-SX", dataRate: "GE", txMedium: "Multimode", fibers: "2 strands", optics: "LC", pathLength: "275/550 m", Tx: "850", Rx: "850" },
    { Model: "SFP-ZX", dataRate: "GE", txMedium: "Singlemode", fibers: "2 strands", optics: "LC", pathLength: "70 km", Tx: "1550", Rx: "1550" }
  ];

export default SFPProducts;